spring:
  application:
    name: adg-rule
  profiles:
    active: prod  #切换至 dev 即可输出调试信息

logging:
  file:
    path: ./logs

application:
  config:
    expected_quantity: 2000000  #预期规则数量
    fault_tolerance: 0.001 #容错率
    warn_limit: 7 #警告阈值, 规则长度小于该值时会输出警告日志
    batch_size: 10000 #写入文件的批次大小

  # 规则源配置，remote为远程规则，local为本地规则，支持多个规则源
  rule:

    # 仅支持 http/https，不限定响应内容格式
    remote:
#      - name: 'example rule' #规则名称
#        path: 'https://example.org/rule.txt' #规则地址
#      - 'https://example.org/rule2.txt' #旧版写法, 不推荐
      - name: 'antiadblockfilters.txt' 
        path: 'https://easylist-downloads.adblockplus.org/antiadblockfilters.txt' 
      - name: 'easylist.txt' 
        path: 'https://easylist-downloads.adblockplus.org/easylist.txt'
      - name: 'easylistchina.txt' 
        path: 'https://easylist-downloads.adblockplus.org/easylistchina.txt'
      - name: 'adguard_optimized.txt' 
        path: 'https://filters.adtidy.org/android/filters/15_optimized.txt'
      - name: 'Adguard_Chinese.txt' 
        path: 'https://filters.adtidy.org/extension/ublock/filters/224.txt'
      - name: 'Adguard_mobile.txt' 
        path: 'https://filters.adtidy.org/extension/ublock/filters/11.txt'
      - name: 'abpmerge.txt' 
        path: 'https://www.gitlink.org.cn/api/damengzhu/abpmerge/raw?filepath=abpmerge.txt'
      - name: 'githubAccelerateHosts.txt' 
        path: 'https://github.com/Potterli20/file/releases/download/github-hosts/Accelerate-Hosts.txt'
      - name: 'anti-ad.txt' 
        path: 'https://anti-ad.net/easylist.txt'
      - name: 'yhosts.txt' 
        path: 'https://github.com/VeleSila/yhosts/raw/master/hosts'
      - name: 'adblockfilters.txt' 
        path: 'https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockfilters.txt'
      - name: 'Steam520.txt' 
        path: 'https://raw.githubusercontent.com/pboymt/Steam520/main/hosts'        
      - name: 'Ad-set-hosts.txt' 
        path: 'https://raw.githubusercontent.com/rentianyu/Ad-set-hosts/master/adguard'  
      - name: '1007.txt' 
        path: 'https://gitcode.net/weixin_45617236/10007_auto/-/raw/Feature/all' 
      - name: '1007ad_auto.txt' 
        path: 'https://gitcode.net/weixin_45617236/adblock_auto/-/raw/main/Rules/adblock_auto.txt' 
      - name: '夕阳醉歌.txt' 
        path: 'https://lingeringsound.github.io/adblock_auto/Rules/adblock_auto_lite.txt' 
      - name: 'Toutiao_block.txt' 
        path: 'https://raw.fgit.ml/lingeringsound/adblock/master/Toutiao_block.txt' 
      - name: 'adblock_plus.txt' 
        path: 'https://raw.githubusercontent.com/uniartisan/adblock_list/master/adblock_plus.txt' 
      - name: 'adblock_privacy.txt' 
        path: 'https://raw.githubusercontent.com/uniartisan/adblock_list/master/adblock_privacy.txt' 
      - name: '乘风.txt' 
        path: 'https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/rule.txt' 
      - name: '乘风-视频.txt' 
        path: 'https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/mv.txt' 
      - name: 'ADgk_banbendalao.txt' 
        path: 'https://raw.githubusercontent.com/banbendalao/ADgk/master/ADgk.txt' 
      - name: 'kill-baidu-ad_banbendalao.txt' 
        path: 'https://raw.githubusercontent.com/banbendalao/ADgk/master/kill-baidu-ad.txt' 
      - name: 'GitHub.txt' 
        path: 'https://raw.githubusercontent.com/jianboy/github-host/master/hosts' 
      - name: '几十KB的轻量规则.txt' 
        path: 'https://raw.githubusercontent.com/damengzhu/banad/main/jiekouAD.txt' 
      - name: '知乎.txt' 
        path: 'https://raw.githubusercontent.com/zsakvo/AdGuard-Custom-Rule/master/rule/zhihu-strict.txt' 
      - name: 'oisd.txt' 
        path: 'https://small.oisd.nl/' 
      - name: 'QuarkList.txt' 
        path: 'https://raw.githubusercontent.com/francis-zhao/quarklist/master/dist/quarklist.txt'        
      - name: 'neodevhost.txt' 
        path: 'https://raw.githubusercontent.com/neodevpro/neodevhost/master/lite_adblocker'  
      - name: 'AdRules.txt' 
        path: 'https://raw.githubusercontent.com/Cats-Team/AdRules/main/adblock_lite.txt'  
      - name: 'ineo6-github.txt' 
        path: 'https://gitlab.com/ineo6/hosts/-/raw/master/next-hosts'  
      - name: 'GitHub520.txt' 
        path: 'https://raw.hellogithub.com/hosts'  
      - name: 'NoAppDownload.txt' 
        path: 'https://raw.githubusercontent.com/Noyllopa/NoAppDownload/master/NoAppDownload.txt'  
      - name: '大圣净化.txt' 
        path: 'https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts'  
      - name: 'AWAvenue-Adblock-Rule.txt' 
        path: 'https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Adblock-Rule/main/AWAvenue-Adblock-Rule.txt'  
      - name: 'halflife-list.txt' 
        path: 'https://cdn.jsdelivr.net/gh/sbwml/halflife-list@master/ad.txt'  
      - name: '晴雅 adg.txt' 
        path: 'http://rssv.cn/adguard/api.php?type=dns'  
      

      
    #本地规则请将文件放置到项目路径rule目录中
    local:
#      - name: 'local rule'
#        path: 'local-rule.txt'
      - name: 'local rule'
        path: 'local-rule.txt'
  output:
    file_header: |  #输出文件头, 占位符${name}将被替换为文件名，如all.txt,  ${date} 将被替换为当前日期
      [ADFS Adblock List]
      ! Title: ${name}
      ! Last Modified: ${date}
      ! Homepage: https://github.com/fordes123/ad-filters-subscriber/
    path: rule   #规则文件输出路径，相对路径默认从 项目目录开始
    files:
      all.txt: #输出文件名
        - DOMAIN  #域名规则，仅完整域名
        - REGEX   #正则规则，包含正则的域名规则，AdGH支持
        - MODIFY  #修饰规则，添加了一些修饰符号的规则，AdG支持
        - HOSTS   #Hosts规则
      dns.txt:
        - DOMAIN
        - REGEX
        - HOSTS
      hosts.txt:
        - HOSTS
      regex.txt:
        - REGEX
      domain.txt:
        - DOMAIN
      modify.txt:
        - MODIFY
